### PR TITLE
#15 - add property namer strategy

### PR DESCRIPTION
**Pull request by ixarlie**
Issue #15

### CODE REVIEW

**Comment by trappar** [comment]
This looks great! Any chance you could add some documentation for it?

**Comment by ixarlie** [comment]
Sure!

@trappar  do you think the PropertyNamer should live in the FixtureGenerationContext class (like the ReferenceNamer)? I wasn't sure where to place it but it makes sense to me now that I am reviewing the code.

**Comment by trappar** [comment]
Hmm... I might have to think a bit about it since I haven't worked on this project once in a while. The question is - is the PropertyNamer a setup step or is it runtime configuration?

If I remember correctly the reason why ReferenceNamer is in the FixtureGenerationContext class is because it's quite possible that from run to run you might want to change how you name references. Is PropertyNamer similar? I'm not sure. What do you think?

**Comment by ixarlie** [comment]
Now that you are saying it, actually, we are "normalizing/serializing" objects. So the way of naming properties should not be changed on runtime. Looking at other serializer solutions, the naming strategy is not a "context" thing.

I will add some documentation for this.

Thanks!

**Comment by ixarlie** [comment]
Hi @trappar ,

If you don't see any other issue, I think it is ready.

Thanks!

**Comment by trappar** [comment]
Merged!

**Comment by ixarlie** [comment]
@trappar could we create a new release including this?

**Comment by trappar** [comment]
Done

**Pull request merged**
